Correspondance/Controllers/AccessController.cs
using CCVCorrespondance.DAL;
using CCVCorrespondance.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CCVCorrespondance.Controllers
{
    public class AccessController : Controller
    {
        private CorrespondanceDB db = new CorrespondanceDB();
        //
        // GET: /Access/
        [SharePointContextFilter]
        public ActionResult Index()
        {

            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InUsersRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("user")).Count() > 0 ? "true" : "false";

            if ((ViewData["InUsersRole"] != "true") && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "Correspondance", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }

            var model = db.tblAccess
            .ToList();

            var modelsorted = model.OrderBy(r => r.AccessGroup).ThenBy(e => e.UserName).ToList();

            return View(modelsorted);
        }


        // GET: /Access/Create
        [SharePointContextFilter]
        public ActionResult Create()
        {

            string[] AccessGroupsModel = ConfigurationManager.AppSettings.AllKeys
                                         .Where(key => key.Contains("Group"))
                                         .Select(key => ConfigurationManager.AppSettings[key])
                                         .ToArray();

            SelectList AGNames = new SelectList(AccessGroupsModel);
            ViewData["AGNames"] = AGNames;

            Access model = new Access();

            return View(model);
        }

        // POST: /Access/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SharePointContextFilter]
        public async Task<ActionResult> Create([Bind(Include = "Id,AccessGroup,UserId,UserName")] Access access)
        {

            if (ModelState.IsValid)
            {

                var accessCount = db.tblAccess
                    .Where(r => r.UserName == access.UserName && r.AccessGroup == access.AccessGroup)
                .ToList();

                int totalRowsCount = accessCount.Count();

                if (totalRowsCount == 0)
                {
                    access.UserId = GetUserId(access.UserName);
                    db.tblAccess.Add(access);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
                }
                else
                {
                    return RedirectToAction("Alert", "Correspondance", new { alertMessage = "User access for " + access.UserName + " as " + access.AccessGroup + " is already defined.", SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
                }

            }

            string[] AccessGroupsModel = ConfigurationManager.AppSettings.AllKeys
                                         .Where(key => key.Contains("Group"))
                                         .Select(key => ConfigurationManager.AppSettings[key])
                                         .OrderBy(key => ConfigurationManager.AppSettings[key])
                                         .ToArray();
            SelectList AGNames = new SelectList(AccessGroupsModel);
            ViewData["AGNames"] = AGNames;

            return View(access);
        }

        // GET: /ALRS/Delete/5
        [SharePointContextFilter]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Alert", "Correspondance", new { alertMessage = "Access control not found, contact administrator.", SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }
            Access alrs = db.tblAccess.Find(id);
            if (alrs == null)
            {
                return RedirectToAction("Alert", "Correspondance", new { alertMessage = "Access control not found, contact administrator.", SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }
            return View(alrs);
        }

        // POST: /ALRS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Access access = db.tblAccess.Find(id);
            db.tblAccess.Remove(access);
            db.SaveChanges();
            return RedirectToAction("Index", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
        }

        public string GetUserId(string user)
        {
            string uid = "";

            PrincipalContext ctx = new PrincipalContext(ContextType.Domain, ConfigurationManager.AppSettings["ADDomain"], ConfigurationManager.AppSettings["ADConnectionUserName"], ConfigurationManager.AppSettings["ADConnectionPassword"]);
            UserPrincipal u = UserPrincipal.FindByIdentity(ctx, user);
            if (u != null)
            {
                uid = u.SamAccountName;
            }
            return uid;
        }

        public static DirectoryEntry GetDirectoryEntry()
        {
            DirectoryEntry de = new DirectoryEntry();
            de.Path = ConfigurationManager.AppSettings["ADConnection"];
            de.AuthenticationType = AuthenticationTypes.Secure;
            return de;
        }


        public JsonResult getUsers(string term)
        {

            DirectoryEntry de = GetDirectoryEntry();
            DirectorySearcher deSearch = new DirectorySearcher();
            List<string> groupMembers = new List<string>();

            de.Password = ConfigurationManager.AppSettings["ADConnectionPassword"];
            de.Username = ConfigurationManager.AppSettings["ADConnectionUserName"];

            deSearch.SearchRoot = de;
            deSearch.Filter = "(&(objectClass=user) (cn=" + "*" + "))";

            foreach (SearchResult sr in deSearch.FindAll())
            {
                foreach (string str in sr.Properties["name"])
                {

                    PrincipalContext ctx = new PrincipalContext(ContextType.Domain, ConfigurationManager.AppSettings["ADDomain"], ConfigurationManager.AppSettings["ADConnectionUserName"], ConfigurationManager.AppSettings["ADConnectionPassword"]);
                    UserPrincipal u = UserPrincipal.FindByIdentity(ctx, str);
                    if (u.EmailAddress != null)
                    { groupMembers.Add(str); }

                }
            }

            return Json(groupMembers, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Alert(string alertMessage)
        {
            TempData["alertMessage"] = alertMessage;
            return View();
        }
    
    }
}

Correspondance/Controllers/CorrespondanceReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CCVCorrespondance.Models;
using CCVCorrespondance.DAL;
using System.Configuration;

namespace CCVCorrespondance.Controllers
{
    public class CorrespondanceReportController : Controller
    {
        private CorrespondanceDB db = new CorrespondanceDB();

        // GET: /CorrespondanceReport/
        [HttpGet]
        [SharePointContextFilter]
        public ActionResult Index()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InUsersRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("user")).Count() > 0 ? "true" : "false";

            if ((ViewData["InUsersRole"] != "true") && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "Correspondance", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }

            var correspondanceTypeModel = getCorrespondanceTypes();
            SelectList CTRNames = new SelectList(correspondanceTypeModel);
            ViewData["CTRNames"] = CTRNames;

            return View(db.CorrespondanceReport.ToList());
        }


        [HttpPost]
        [SharePointContextFilter]
        public ActionResult Index(DateTime SSDate1, DateTime SEDate1, string CorrespondanceReportTypeName)
        {

            return RedirectToAction("Report", "Report", new { SSDate = SSDate1, SEDate = SEDate1, SType = CorrespondanceReportTypeName, SFlag = "Generate", SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
           // return View();
        }

        [SharePointContextFilter]
        public ActionResult ShowCorrespondanceReport(DateTime startDate, DateTime endDate)
        {

            return View(db.CorrespondanceReport.ToList());
        }

        // GET: /CorrespondanceReport/Details/5
        [SharePointContextFilter]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CorrespondanceReport correspondancereport = db.CorrespondanceReport.Find(id);
            if (correspondancereport == null)
            {
                return HttpNotFound();
            }
            var correspondanceTypeModel = getCorrespondanceTypes();
            SelectList CTRNames = new SelectList(correspondanceTypeModel);
            ViewData["CTRNames"] = CTRNames;
            return View(correspondancereport);
        }


        private List<string> getCorrespondanceTypes()
        {
            List<string> model = db.CorrespondanceTypes
                .Select(r => r.CorrespondanceTypeName).ToList();
            model.Add("All");
            return model;
        }


        // GET: /CorrespondanceReport/Create
        [SharePointContextFilter]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /CorrespondanceReport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,CorrespondanceReportUser,CorrespondanceReportStartDate,CorrespondanceReportEndDate,CorrespondanceReportTypeName,CorrespondanceReceivedOrSentDate,CorrespondanceReportFromTo,CorrespondanceReportDepartment,CorrespondanceReportSubject")] CorrespondanceReport correspondancereport)
        {
            if (ModelState.IsValid)
            {
                db.CorrespondanceReport.Add(correspondancereport);
                db.SaveChanges();
                return RedirectToAction("Index", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }

            return View(correspondancereport);
        }

        // GET: /CorrespondanceReport/Edit/5
        [SharePointContextFilter]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CorrespondanceReport correspondancereport = db.CorrespondanceReport.Find(id);
            if (correspondancereport == null)
            {
                return HttpNotFound();
            }
            return View(correspondancereport);
        }

        // POST: /CorrespondanceReport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,CorrespondanceReportUser,CorrespondanceReportStartDate,CorrespondanceReportEndDate,CorrespondanceReportTypeName,CorrespondanceReceivedOrSentDate,CorrespondanceReportFromTo,CorrespondanceReportDepartment,CorrespondanceReportSubject")] CorrespondanceReport correspondancereport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(correspondancereport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }
            return View(correspondancereport);
        }

        // GET: /CorrespondanceReport/Delete/5
        [SharePointContextFilter]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CorrespondanceReport correspondancereport = db.CorrespondanceReport.Find(id);
            if (correspondancereport == null)
            {
                return HttpNotFound();
            }
            return View(correspondancereport);
        }

        // POST: /CorrespondanceReport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CorrespondanceReport correspondancereport = db.CorrespondanceReport.Find(id);
            db.CorrespondanceReport.Remove(correspondancereport);
            db.SaveChanges();
            return RedirectToAction("Index", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Correspondance/Views/Shared/Alert.cshtml
@model CCVCorrespondance.Models.Correspondance

@{
    ViewBag.Title = "Correspondance Alert";
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()


    <h2></h2>
    <table border="0">
        <tr>
            @*<td class="auto-style15" style="text-align: left">
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn btn-primary" })
            </td>*@

            </tr>
        </table>


        @Html.Raw(TempData["alertMessage"])

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Correspondance/Views/Shared/Unauthorised.cshtml
@{
    ViewBag.Title = "Correspondance - Unauthorised";
}

@*@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()*@

<h2></h2>    
<h2></h2>
<h4>You are not authorised to view this application. Please contact the administrator.</h4>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@



Correspondance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" charset="utf-8">
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CCV Correspondance</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/custom")
    <link href='@ViewBag.SPHostUrl/_layouts/15/defaultcss.ashx' type='text/css' rel='stylesheet' />
    <script src='@ViewBag.SPHostUrl/_layouts/15/SP.UI.Controls.js'></script>
</head>

<body style="overflow: auto;">
    <div id="chrome_ctrl_container"></div>
    <div class="navbar">
        <div class="container">
            @*<h2>Welcome @ViewBag.UserName!</h2>*@
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)</li>
                @if (ViewData["InOwnerRole"] == "true")
                {
                    <li>@Html.ActionLink("Access Control", "Index", "Access", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)</li>
                    <li>@Html.ActionLink("Report", "Index", "CorrespondanceReport", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)</li>
                }
                <li>@Html.ActionLink("About", "About", "Home", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="navbar-text">Hello, @User.Identity.Name!</li>
            </ul>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        @RenderSection("DocumentLog", required: false) <br /> <br />
        <footer>
            <p>&copy; @DateTime.Now.Year - CCV Correspondance<span style="float:right;"><input type="image" class="HomeFooterlogo" style="height:50px;" /></span> </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>



@*<!DOCTYPE html>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" charset="utf-8">
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - CCV Correspondance</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/custom")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <input type="image" class="Homelogo" style="width:130px;" />
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(" Home", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (ViewData["InOwnerRole"] == "true" || ViewData["InUsersRole"] == "true")
                        {
                            <li>@Html.ActionLink("Access Control", "Index", "Access")</li>
                            <li>@Html.ActionLink("Report", "Index", "CorrespondanceReport")</li>
                        }
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="navbar-text">Hello, @User.Identity.Name!</li>
                    </ul>
                </div>
            </div>
        </div>


        <div class="container body-content">
            @RenderBody()
            <hr />
            @RenderSection("DocumentLog", required: false) <br /> <br />
            <footer>
                <p>&copy; @DateTime.Now.Year - CCV Correspondance <span style="float:right;"><input type="image" class="HomeFooterlogo" style="height:50px;" /></span> </p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@