Correspondance/Controllers/HomeFromController.cs
using CCVCorrespondance.DAL;
using CCVCorrespondance.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CCVCorrespondance.Controllers
{
    public class HomeFromController : Controller
    {

        CorrespondanceDB _db;

        public HomeFromController()
        {
            _db = new CorrespondanceDB();

        }

        public HomeFromController(CorrespondanceDB db)
        {
            _db = db;
        }

        public class JQueryDataTableParamModel
        {
            public string sEcho { get; set; }
            public string sSearch { get; set; }
            public int iDisplayLength { get; set; }
            public int iDisplayStart { get; set; }
            public string first_data { get; set; }
            public string second_data { get; set; }
        }

        public JsonResult GetAjaxData(JQueryDataTableParamModel param)
        {

            var model = _db.Correspondances
               .Where(r => r.DocumentDeleted == false)
               .Select(r => new CorrespondanceFromToVM { VM_FromTo = r.CorrespondanceFromTo, VM_Type = r.CorrespondanceType, VM_Year = r.CorrespondanceYear, VM_Department = r.CorrespondanceDepartment, VM_Subject = r.CorrespondanceSubject, VM_DateOnLetter = r.CorrespondanceDateOnLetter, VM_DateReceivedOrSent = r.CorrespondanceDateReceivedOrSent, VM_Id = r.ID })
                .ToList();

            List<CorrespondanceFromToVM> modelsorted;

            int totalRowsCount = 0;
            int filteredRowsCount = 0;
            string[][] aaData;

            if (param.first_data != null && param.second_data != null)
            {
                List<CorrespondanceFromToVM> aa = new List<CorrespondanceFromToVM>();
                foreach (var group in model)
                {
                    var test = group.VM_FromTo.Replace(" ", "").Trim('-').ToLower();
                    var test1 = test.Replace(",", "").Trim('-').ToLower();
                    if (test1.Contains(param.first_data) &&
                        group.VM_Type.ToLower().Contains(param.second_data.Trim()))
                        aa.Add(group);
                }

                modelsorted = aa.OrderBy(r => r.VM_FromTo).ThenBy(e => e.VM_Type).ToList();
                aa = null;
                aaData = modelsorted.Select(d => new string[] { d.VM_FromTo, d.VM_Type, d.VM_Year.ToString(), d.VM_Department, d.VM_Subject, (d.VM_DateOnLetter.HasValue ? d.VM_DateOnLetter.Value.ToString("dd-MM-yyyy") : d.VM_DateOnLetter.ToString()), d.VM_DateReceivedOrSent.ToString("dd-MM-yyyy"), d.VM_Id.ToString() }).ToArray();

                totalRowsCount = modelsorted.Count();
                filteredRowsCount = modelsorted.Count();

                return Json(new
                {
                    sEcho = param.sEcho,
                    aaData = aaData,
                    iTotalRecords = Convert.ToInt32(totalRowsCount),
                    iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
                }, JsonRequestBehavior.AllowGet);


            }

            if (param.sSearch != null)
            {
                if (param.sSearch.Length > 2)
                {

                    List<CorrespondanceFromToVM> aa = new List<CorrespondanceFromToVM>();
                    foreach (var group in model)
                    {
                        if (group.VM_Type.ToLower().Contains(param.sSearch.ToLower()) || group.VM_Year.ToString().Contains(param.sSearch.ToLower()) || group.VM_Department.ToLower().Contains(param.sSearch.ToLower()) ||
                            group.VM_Subject.ToLower().Contains(param.sSearch.ToLower()))

                            aa.Add(group);

                    }

                    modelsorted = aa.OrderBy(r => r.VM_FromTo).ThenBy(e => e.VM_Type).ThenBy(e => e.VM_Year).ToList();
                    aa = null;
                    aaData = modelsorted.Select(d => new string[] { d.VM_FromTo, d.VM_Type, d.VM_Year.ToString(), d.VM_Department, d.VM_Subject, (d.VM_DateOnLetter.HasValue ? d.VM_DateOnLetter.Value.ToString("dd-MM-yyyy") : d.VM_DateOnLetter.ToString()), d.VM_DateReceivedOrSent.ToString("dd-MM-yyyy"), d.VM_Id.ToString() }).ToArray();

                    totalRowsCount = modelsorted.Count();
                    filteredRowsCount = modelsorted.Count();

                    return Json(new
                    {
                        sEcho = param.sEcho,
                        aaData = aaData,
                        iTotalRecords = Convert.ToInt32(totalRowsCount),
                        iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
                    }, JsonRequestBehavior.AllowGet);
                }

            }

            totalRowsCount = model.Count();
            filteredRowsCount = model.Count();
            var vv = model.Select(r => new { r.VM_FromTo, r.VM_Type }).Distinct().OrderBy(r => r.VM_FromTo).ThenBy(e => e.VM_Type).ToList();

            aaData = vv.Select(d => new string[] { d.VM_FromTo, d.VM_Type, "", "", "", "", "", "" }).ToArray();


            return Json(new
            {
                sEcho = param.sEcho,
                aaData = aaData,
                iTotalRecords = Convert.ToInt32(totalRowsCount),
                iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
            }, JsonRequestBehavior.AllowGet);

        }
        [SharePointContextFilter]
        public ActionResult Index()
        {

            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = _db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InUsersRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("user")).Count() > 0 ? "true" : "false";

            if ((ViewData["InUsersRole"] != "true") && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "Correspondance", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }

            var model = _db.Correspondances
                 .Where(a => a.DocumentDeleted == false)
                .ToList();

            return View(model);
        }

        [SharePointContextFilter]
        public ActionResult About()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = _db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InUsersRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("user")).Count() > 0 ? "true" : "false";

            if ((ViewData["InUsersRole"] != "true") && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "Correspondance", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }
            ViewBag.Message = "CCV Correspondance";

            return View();
        }

        [SharePointContextFilter]
        public ActionResult Contact()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = _db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InUsersRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("user")).Count() > 0 ? "true" : "false";

            if ((ViewData["InUsersRole"] != "true") && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "Correspondance", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //public ActionResult Report()
        //{
        //    ViewBag.Message = "Report";

        //    return View();
        //}


        [HttpGet]
        [SharePointContextFilter]
        public ActionResult Create()
        {

            return View();
        }

        // POST: /Document/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DocumentId,SubCategoryId,DocumentName,BusinessUnit,Body,DateCreated,CreatedBy")] Correspondance correspondance)
        {
            if (ModelState.IsValid)
            {
                _db.Correspondances.Add(correspondance);
                await _db.SaveChangesAsync();

Correspondance/Views/HomeFrom/Index.cshtml
@model IEnumerable<CCVCorrespondance.Models.Correspondance>

@{
    ViewBag.Title = "Home Page";
}

<div id="container">

    @*<h2>Correspondances</h2>*@

    @*<select style="border:none;" name='PreviousReceiver' onchange='if (this.value == "Received") { window.location.href = "../Correspondance/Create?ctype=" + this.value + "&cyear=" + Date.now() } else { window.location.href = "../Correspondance/Create?ctype=" + this.value + "&cyear=" + new Date.getFullYear() }'>
            <option value="">New Correspondance</option>
            <option value='Received'>Received</option>
            <option value='Sent'>Sent</option>
        </select>*@


    <p>
        <input type="image" class="NewDoclogo" />
        @Html.ActionLink("New - Correspondance Received", "Create", "Correspondance", new { ctype = "Received", cyear = DateTime.Now.Year, SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null) <a id="tab4"></a>
        <input type="image" class="NewDoclogo" />
        @Html.ActionLink("New - Correspondance Sent", "Create", "Correspondance", new { ctype = "Sent", cyear = DateTime.Now.Year, SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null) <a id="tab4"></a>
    </p>

    <table border="0">
        <tr>
            <td class="auto-style20">
                <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; background-color: whitesmoke; width: 100%; height: 100%;">
                    <tr style="background-color: darkblue; color: white"><th align="center" class="auto-style19"><b>Correspondance</b></th></tr>
                    <tr>
                        <td class="auto-style2">
                            <table border="0" style="font-family: Arial; font-size: 12pt; width: 100%; background-color: white;" cellspacing="0" cellpadding="0">
                                <tr style="">
                                    <td align="left" valign="top">
                                        <p>
                                            @if ((ViewData["InUsersRole"] == "true") || ViewData["InOwnerRole"] == "true")
                                            {
                                                <img src="~/Content/icons/menuitem.jpg" style="float:left;">
                                                @Html.ActionLink("All", "Index", "Home", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)}
                                        </p>
                                        <p></p>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="left" valign="top">
                                        <p>
                                            @if ((ViewData["InUsersRole"] == "true") || ViewData["InOwnerRole"] == "true")
                                            {
                                                <img src="~/content/icons/menuitem.jpg" style="float:left;">
                                                @Html.ActionLink("Date", "Index", "HomeDate", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)}
                                        </p>
                                        <p></p>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="left" valign="top">
                                        <p>
                                            @if ((ViewData["InUsersRole"] == "true") || ViewData["InOwnerRole"] == "true")
                                            {
                                                <img src="~/content/icons/menuitem.jpg" style="float:left;">
                                                @Html.ActionLink("Department", "Index", "HomeDepartment", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)}
                                        </p>
                                        <p></p>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="left" valign="top">
                                        <p>
                                            @if ((ViewData["InUsersRole"] == "true") || ViewData["InOwnerRole"] == "true")
                                            {
                                                <img src="~/content/icons/menuitem.jpg" style="float:left;">
                                                @Html.ActionLink("From", "Index", "HomeFrom", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)}
                                        </p>
                                        <p></p>
                                    </td>
                                </tr>

                                <tr>
                                    <td align="left" valign="top">
                                        <p>
                                            @if ((ViewData["InUsersRole"] == "true") || ViewData["InOwnerRole"] == "true")
                                            {
                                                <img src="~/content/icons/menuitem.jpg" style="float:left;">
                                                @Html.ActionLink("Subject", "Index", "HomeSubject", new { SPHostUrl = SharePointContext.GetSPHostUrl(HttpContext.Current.Request).AbsoluteUri }, null)}
                                        </p>
                                        <p></p>
                                    </td>
                                </tr>

                                @*@Html.DropDownList("ALRSRequestorPosition", ViewData["HRPNames"] as SelectList, new { onchange = "document.location.href = '/Home/Index?rp=' + this.options[this.selectedIndex].value;" })*@
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    @*</td>*@

    @*Server side datatables*@
    <td class="auto-style1">
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; background-color: whitesmoke; width: 100%; ">
            <tr style="background-color: darkblue; color: white"><th align="center" class="auto-style19"><b></b>View</th></tr>
        </table>

        <table id="examplefromto" border="0" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Type</th>
                    <th>Year</th>
                    <th>From/To</th>
                    <th>Subject</th>
                    <th>Date on Letter</th>
                    <th>Date Received/Sent</th>
                    @*<th>Id</th>*@
                </tr>
            </thead>
        </table>
    </td>

    @*<td class="auto-style1">
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; background-color: whitesmoke; width: 100%; ">
            <tr style="background-color: darkblue; color: white"><th align="center" class="auto-style19"><b>View All</b></th></tr>

        </table>

        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; background-color:whitesmoke; width:100%; ">

            <tr style="background-color: lightgoldenrodyellow; color: black">
            </tr>

            <tr>
                <div id="demo">
                    <table id="example" border="0" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.CorrespondanceType)</th>
                                <th>@Html.DisplayNameFor(model => model.CorrespondanceYear)</th>
                                <th id="tab2">@Html.DisplayNameFor(model => model.CorrespondanceFromTo)</th>
                                <th id="tab3">@Html.DisplayNameFor(model => model.CorrespondanceDepartment)</th>
                                <th id="tab4">@Html.DisplayNameFor(model => model.CorrespondanceSubject)</th>
                                <th id="tab5">@Html.DisplayNameFor(model => model.CorrespondanceDateOnLetter)</th>
                                <th id="tab6">@Html.DisplayNameFor(model => model.CorrespondanceDateReceivedOrSent)</th>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                            </tr>
                        </tfoot>


                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class=@Html.Raw('"')@item.CorrespondanceType@Html.Raw('"') id=@Html.Raw('"')@item.CorrespondanceYear@Html.Raw('"')>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceType)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceYear)</td>
                                    <td id="tab2">@Html.ActionLink(item.CorrespondanceFromTo, "Details", "Correspondance", new { id = item.ID, ctype = item.CorrespondanceType }, new { ctype = item.CorrespondanceType })</td>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceDepartment)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceSubject)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceDateOnLetter)</td>
                                    <td>@Html.DisplayFor(modelItem => item.CorrespondanceDateReceivedOrSent)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </tr>
        </table>*@

    <table border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
        </thead>
    </table>